# Generated by Django 3.2.14 on 2023-02-11 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organasation_Name', models.CharField(max_length=255)),
                ('Organasation_Type', models.CharField(choices=[('Oldage Home', 'Oldage Home'), ('Orphenage', 'Orphanage'), ('Other', 'Other')], max_length=255)),
                ('Place', models.CharField(max_length=255)),
                ('Contry', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Registration_Number', models.CharField(max_length=255)),
                ('Number_of_members', models.IntegerField()),
                ('Date_of_Registration', models.DateField()),
                ('Registration_Document', models.FileField(upload_to='Registration_documents')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
