# Generated by Django 3.2.14 on 2023-02-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgdetails',
            name='Phone_Number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
