# Generated by Django 3.2.14 on 2023-02-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_orgdetails_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgdetails',
            name='activation_status',
            field=models.BooleanField(default=False),
        ),
    ]
