# Generated by Django 3.2.14 on 2023-02-11 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=255)),
                ('Brand', models.CharField(max_length=255)),
                ('Category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kid', 'Kid')], max_length=20)),
                ('Discription', models.CharField(max_length=1000)),
                ('Price', models.PositiveBigIntegerField()),
                ('Stock', models.IntegerField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Shop_Name', models.CharField(max_length=255)),
                ('Image', models.ImageField(upload_to='product_image')),
                ('status', models.BooleanField(default=True)),
                ('Merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
